GO
IF(EXISTS (SELECT NAME FROM SYSOBJECTS
WHERE NAME = 'TR_STUDENT_INSERT' AND TYPE = 'TR'))
	DROP TRIGGER TR_STUDENT_INSERT
GO
CREATE TRIGGER TR_STUDENT_INSERT
ON STUDENT
FOR INSERT
AS BEGIN
	INSERT INTO STUDENT_ACCOUNT
	SELECT STUDENT_ID,'1' PWD, GETDATE() CREATED_DATE, 0 IS_ACTIVE
	FROM inserted
END
