GO
IF(EXISTS (SELECT NAME FROM SYSOBJECTS
WHERE NAME = 'TR_STUDENT_INSERT' AND TYPE = 'TR'))
	DROP TRIGGER TR_STUDENT_INSERT
GO
CREATE TRIGGER TR_STUDENT_INSERT
ON STUDENT
FOR INSERT
AS BEGIN
	DECLARE @ID VARCHAR(10);
	SET @ID = (SELECT STUDENT_ID FROM inserted);
	EXEC PR_CREATE_LOGIN @ID,'1'
	INSERT INTO STUDENT_ACCOUNT
	SELECT STUDENT_ID,'1' PWD, GETDATE() CREATED_DATE, 0 IS_ACTIVE
	FROM inserted;
END

--khoa's note (ko ảnh hưởng): chưa add vào azure 
