SELECT CL.CLASS_ID, S.ST_NAME AS STUDENT_NAME, 
	   C.COURSE_NAME, R.OVERALL AS HIGHEST_OVERALL
FROM RESULT R JOIN STUDENT S ON R.STUDENT_ID = S.STUDENT_ID
			  JOIN CLASS CL ON R.CLASS_ID = CL.CLASS_ID
			  JOIN COURSE C ON CL.COURSE_ID = C.COURSE_ID
WHERE R.OVERALL = (
    SELECT MAX(OVERALL)
    FROM RESULT
    WHERE CLASS_ID = R.CLASS_ID
)