WITH COURSE_COUNT AS (
    SELECT C.COURSE_NAME, COUNT(R.STUDENT_ID) AS STUDENT_COUNT
    FROM COURSE C JOIN CLASS CL ON C.COURSE_ID = CL.COURSE_ID
				  JOIN RESULT R ON CL.CLASS_ID = R.CLASS_ID
    GROUP BY C.COURSE_NAME
)
SELECT COURSE_NAME, STUDENT_COUNT
FROM COURSE_COUNT
WHERE STUDENT_COUNT = (SELECT MAX(STUDENT_COUNT) FROM COURSE_COUNT);