SELECT COURSE_NAME, COUNT(R.STUDENT_ID) AS STUDENT_COUNT
FROM COURSE C JOIN CLASS CL ON C.COURSE_ID = CL.COURSE_ID
	      JOIN RESULT R ON CL.CLASS_ID = R.CLASS_ID
GROUP BY C.COURSE_NAME
HAVING COUNT(R.STUDENT_ID) = (
       SELECT MAX(STUDENT_COUNT) 
       FROM (
            SELECT COUNT(R.STUDENT_ID) AS STUDENT_COUNT
            FROM COURSE C JOIN CLASS CL ON C.COURSE_ID = CL.COURSE_ID
			  JOIN RESULT R ON CL.CLASS_ID = R.CLASS_ID
            GROUP BY C.COURSE_NAME
        ) AS MAX_COUNT
)
