SELECT TOP 1 ST.STUDENT_ID, ST.ST_NAME, MIN((ISNULL(R.LISTENING, 0) + ISNULL(R.READING, 0) + ISNULL(R.WRITING, 0) + ISNULL(R.SPEAKING, 0)) / 4) AS MIN_SCORE
FROM STUDENT ST
JOIN RESULT R ON ST.STUDENT_ID = R.STUDENT_ID
JOIN CLASS C ON R.CLASS_ID = C.CLASS_ID
JOIN CLASS_DETAIL CD ON C.CLASS_ID = CD.CLASS_ID
WHERE YEAR(CD.DATE_START) = 2020 AND MONTH(CD.DATE_START) <= 6
GROUP BY ST.STUDENT_ID, ST.ST_NAME
ORDER BY MIN_SCORE;
