SELECT COUNT(CLASS.CLASS_ID) FROM CLASS
JOIN CLASS_DETAIL ON CLASS.CLASS_ID = CLASS_DETAIL.CLASS_ID
JOIN COURSE ON CLASS.COURSE_ID = COURSE.COURSE_ID
WHERE YEAR(CLASS_DETAIL.DATE_START) = 2024
	  AND COURSE.COURSE_TYPE = 'Master';
