SELECT COUNT(CLASS_ID) AS TOTAL_CLASS
FROM CLASS_DETAIL
WHERE (DATEPART(YEAR, DATE_START) = 2024)
	AND (
	(DATEPART(QUARTER, CLASS_DETAIL.DATE_START) = 1) 
	OR (DATEPART(QUARTER, CLASS_DETAIL.DATE_START) = 2)
);
