CREATE DATABASE QLTTTA_11

USE QLTTTA_11

CREATE TABLE TEACHER
(
	TEACHER_ID VARCHAR(10) NOT NULL PRIMARY KEY,
	TR_NAME NVARCHAR(50) NOT NULL,
	TR_NATION NVARCHAR(50) NOT NULL,
	TR_GENDER VARCHAR(5) NOT NULL,
	TR_DATE DATE NOT NULL,
	TR_PHONE VARCHAR(20) NOT NULL,
	TR_EMAIL NVARCHAR(50) NOT NULL,
	TR_ADDRESS NVARCHAR(50) NOT NULL,
	TR_DEGREE NVARCHAR(50) NOT NULL,
	IELTS_OVERALL DECIMAL(3,1) NOT NULL,
)

CREATE TABLE STUDENT
(
	STUDENT_ID VARCHAR(10) NOT NULL PRIMARY KEY,
	ST_NAME NVARCHAR(50) NOT NULL,
	ST_GENDER VARCHAR(5) NOT NULL,
	ST_PHONE VARCHAR(20) NOT NULL,
	ST_ADDRESS NVARCHAR(50) NOT NULL,
	ST_EMAIL NVARCHAR(50) NULL, 
	ST_DATE DATE NOT NULL,
)

CREATE TABLE COURSE
(
	COURSE_ID VARCHAR(10) NOT NULL PRIMARY KEY,
	COURSE_NAME NVARCHAR(50) NOT NULL,
	COURSE_TYPE NVARCHAR(50) NOT NULL,
	COURSE_LEVEL NVARCHAR(50) NOT NULL,
	COURSE_FEE MONEY NOT NULL,
	COURSE_METHOD BIT NOT NULL,
)

CREATE TABLE BILL
(
	BILL_ID VARCHAR(10) NOT NULL PRIMARY KEY,
	STUDENT_ID VARCHAR(10) NOT NULL FOREIGN KEY REFERENCES STUDENT(STUDENT_ID),
	DATE_P DATETIME NOT NULL,
	METHOD_P VARCHAR(50) NOT NULL,
	PAYMENT MONEY NOT NULL,
)

CREATE TABLE CLASS
(
	CLASS_ID VARCHAR(10) NOT NULL PRIMARY KEY,
	COURSE_ID VARCHAR(10) NOT NULL FOREIGN KEY REFERENCES COURSE(COURSE_ID),
	TEACHER_ID VARCHAR(10) NOT NULL FOREIGN KEY REFERENCES TEACHER(TEACHER_ID),
	CLASSROOM VARCHAR(10) NOT NULL,
)

CREATE TABLE TIMETABLE
(
	CLASS_ID VARCHAR(10) NOT NULL,
	WEEKLYDAY SMALLINT NOT NULL,
	DAYPERIOD TIME NOT NULL,
	CONSTRAINT PK_TIMETABLE PRIMARY KEY (CLASS_ID, WEEKLYDAY, DAYPERIOD),
	CONSTRAINT FK_TIMETABLE_CLASS FOREIGN KEY (CLASS_ID) REFERENCES CLASS(CLASS_ID),
)

CREATE TABLE RESULT
(
	STUDENT_ID VARCHAR(10) NOT NULL,
	CLASS_ID VARCHAR(10) NOT NULL,
	LISTENING DECIMAL(3,1) NOT NULL,
	READING DECIMAL(3,1) NOT NULL,
	WRITING DECIMAL(3,1) NOT NULL,
	SPEAKING DECIMAL(3,1) NOT NULL,
	OVERALL DECIMAL(3,1) NOT NULL,
	CONSTRAINT PK_RESULT PRIMARY KEY (STUDENT_ID, CLASS_ID),
	CONSTRAINT FK_RESULT_STUDENT FOREIGN KEY (STUDENT_ID) REFERENCES STUDENT(STUDENT_ID),
	CONSTRAINT FK_RESULT_CLASS FOREIGN KEY (CLASS_ID) REFERENCES CLASS(CLASS_ID),
)

CREATE TABLE CLASS_DETAIL 
(
	CLASS_ID VARCHAR(10) NOT NULL PRIMARY KEY,
	DATE_START DATE NOT NULL,
	DATE_END DATE NOT NULL,
	LESSONS SMALLINT NOT NULL,
	CONSTRAINT FK_CLASS_DETAIL_CLASS FOREIGN KEY (CLASS_ID) REFERENCES CLASS(CLASS_ID),
)

