DELETE FROM STUDENT
WHERE STUDENT_ID NOT IN (
    SELECT DISTINCT BILL.STUDENT_ID
    FROM BILL
    JOIN CLASS_DETAIL ON BILL.CLASS_ID = CLASS_DETAIL.CLASS_ID
    WHERE DATEDIFF(DAY, CLASS_DETAIL.DATE_START, GETDATE()) <= 7
);
