DELETE FROM BILL
WHERE STUDENT_ID IN (
    SELECT DISTINCT BILL.STUDENT_ID
    FROM BILL
    JOIN STUDENT ON STUDENT.STUDENT_ID = BILL.STUDENT_ID
	JOIN RESULT ON RESULT.STUDENT_ID = STUDENT.STUDENT_ID
	JOIN CLASS ON CLASS.CLASS_ID = RESULT.CLASS_ID
	JOIN CLASS_DETAIL ON CLASS.COURSE_ID = CLASS_DETAIL.CLASS_ID
    WHERE DATEDIFF(DAY, CLASS_DETAIL.DATE_START, GETDATE()) > 7
);
DELETE FROM STUDENT
WHERE STUDENT_ID NOT IN (
    SELECT DISTINCT BILL.STUDENT_ID FROM BILL
);
