UPDATE COURSE 
SET COURSE_FEE = 80.00
FROM COURSE
JOIN CLASS ON COURSE.COURSE_ID = CLASS.COURSE_ID
JOIN CLASS_DETAIL ON CLASS.CLASS_ID = CLASS_DETAIL.CLASS_ID
WHERE COURSE.COURSE_TYPE = 'Junior' 
AND YEAR(CLASS_DETAIL.DATE_START) = 2024
AND CLASS_DETAIL.DATE_START = 
(SELECT MIN(DATE_START) FROM CLASS_DETAIL WHERE CLASS_DETAIL.CLASS_ID = CLASS.CLASS_ID);
