UPDATE COURSE
SET COURSE_FEE = 80.00
WHERE COURSE_ID NOT IN (
	SELECT DISTINCT COURSE_ID FROM CLASS
	JOIN CLASS_DETAIL ON CLASS.CLASS_ID = CLASS_DETAIL.CLASS_ID
	WHERE DATEDIFF(MONTH, GETDATE(), DATE_START) < 6
);

