SELECT 
    a.TEACHER_ID,
    TR_NAME,
    COUNT(b.CLASS_ID) AS SoLopDaDay
FROM 
    TEACHER a
JOIN 
    CLASS b ON a.TEACHER_ID = b.TEACHER_ID
GROUP BY 
    a.TEACHER_ID, TR_NAME
HAVING 
    COUNT(b.CLASS_ID) = 3;
