SELECT RESULT.STUDENT_ID, ST_NAME AS STUDENT_NAME, CLASS.CLASS_ID
FROM CLASS_DETAIL JOIN CLASS ON CLASS_DETAIL.CLASS_ID = CLASS.CLASS_ID
				  JOIN RESULT ON CLASS.CLASS_ID = RESULT.CLASS_ID
				  JOIN STUDENT ON RESULT.STUDENT_ID = STUDENT.STUDENT_ID
WHERE DATE_START BETWEEN  '2023-01-01' AND '2023-01-31'
INTERSECT
SELECT RESULT.STUDENT_ID, ST_NAME AS STUDENT_NAME, CLASS.CLASS_ID
FROM CLASS_DETAIL JOIN CLASS ON CLASS_DETAIL.CLASS_ID = CLASS.CLASS_ID
				  JOIN RESULT ON CLASS.CLASS_ID = RESULT.CLASS_ID
				  JOIN STUDENT ON RESULT.STUDENT_ID = STUDENT.STUDENT_ID
WHERE DATE_START BETWEEN '2024-01-01' AND '2024-01-31'