SELECT T.TR_NAME, COUNT(CL.COURSE_ID) AS [NUMBER_OF_COURSE]
FROM TEACHER T, CLASS CL
WHERE T.TEACHER_ID = CL.TEACHER_ID
GROUP BY T.TR_NAME
UNION ALL
SELECT T.TR_NAME, 0 AS [NUMBER_OF_COURSE]
FROM TEACHER T
WHERE T.TEACHER_ID NOT IN (
    SELECT DISTINCT CL.TEACHER_ID
    FROM CLASS CL
);