USE master
CREATE LOGIN TR001 WITH PASSWORD = '1'

USE QLTTTA
CREATE USER TR001 FOR LOGIN TR001
CREATE ROLE teacher;

GRANT SELECT ON TEACHER TO teacher;
GRANT SELECT(STUDENT_ID,ST_NAME,ST_EMAIL,ST_GENDER,ST_DATE) ON STUDENT TO teacher;
GRANT SELECT ON TIMETABLE TO teacher;
GRANT SELECT, UPDATE(SPEAKING,LISTENING,READING,WRITING,OVERALL) ON RESULT TO teacher;
GRANT SELECT ON CLASS_DETAIL TO teacher;
GRANT SELECT ON CLASS TO teacher;
GRANT SELECT ON COURSE TO teacher;
GRANT SELECT ON TEACHER_ACCOUNT TO teacher;

ALTER ROLE teacher ADD MEMBER TR001;
