GO
CREATE PROC PR_RESULT_UPDATE
	@ST_ID VARCHAR(10), 
	@CL_ID VARCHAR(10), 
	@LISTENING DECIMAL(2,1),
	@READING DECIMAL(2,1), 
	@SPEAKING DECIMAL(2,1), 
	@WRITING DECIMAL(2,1)
AS BEGIN
	UPDATE RESULT
	SET SPEAKING = @SPEAKING
		LISTENING = @LISTENING,
		READING = @READING,
		WRITING = @WRITING,
		
	WHERE STUDENT_ID = @ST_ID AND CLASS_ID = @CL_ID
END
