CREATE PROC PR_BILL_CHECK
@OPTION BIT
AS BEGIN
	IF @OPTION = 1 -- LẤY RA HS CHƯA ĐÓNG TIỀN
	BEGIN
		SELECT A.STUDENT_ID, E.ST_NAME, A.CLASS_ID, C.COURSE_ID, COURSE_FEE, DATE_START
		FROM RESULT A
		JOIN CLASS B ON A.CLASS_ID = B.CLASS_ID
		JOIN COURSE C ON B.COURSE_ID = C.COURSE_ID
		JOIN CLASS_DETAIL D ON B.CLASS_ID = D.CLASS_ID
		JOIN STUDENT E ON A.STUDENT_ID = E.STUDENT_ID
		WHERE A.STUDENT_ID NOT IN (SELECT A.STUDENT_ID
			FROM BILL A 
			JOIN RESULT B ON A.STUDENT_ID = B.STUDENT_ID
			JOIN CLASS_DETAIL C ON B.CLASS_ID = C.CLASS_ID
			WHERE DATEDIFF(DAY,DATE_START,DATE_P) >= 0)
	END
	ELSE
	BEGIN
		SELECT A.STUDENT_ID, E.ST_NAME, A.CLASS_ID, C.COURSE_ID, COURSE_FEE, DATE_START, FORMAT(GETDATE(),'yyyy-MM-dd') TODAY
		FROM RESULT A
		JOIN CLASS B ON A.CLASS_ID = B.CLASS_ID
		JOIN COURSE C ON B.COURSE_ID = C.COURSE_ID
		JOIN CLASS_DETAIL D ON B.CLASS_ID = D.CLASS_ID
		JOIN STUDENT E ON A.STUDENT_ID = E.STUDENT_ID
		WHERE A.STUDENT_ID NOT IN (SELECT A.STUDENT_ID
			FROM BILL A 
			JOIN RESULT B ON A.STUDENT_ID = B.STUDENT_ID
			JOIN CLASS_DETAIL C ON B.CLASS_ID = C.CLASS_ID
			WHERE DATEDIFF(DAY,DATE_START,DATE_P) >= 0)
		AND DATEDIFF(DAY,DATE_START,GETDATE()) > 7 -- QUÁ 7 NGÀY THÌ XÓA

		DELETE RESULT
		FROM CLASS_DETAIL 
		WHERE STUDENT_ID NOT IN (SELECT A.STUDENT_ID
			FROM BILL A 
			JOIN RESULT B ON A.STUDENT_ID = B.STUDENT_ID
			JOIN CLASS_DETAIL C ON B.CLASS_ID = C.CLASS_ID
			WHERE DATEDIFF(DAY,DATE_START,DATE_P) >= 0)
		AND DATEDIFF(DAY,DATE_START,GETDATE()) > 7 
		AND RESULT.CLASS_ID = CLASS_DETAIL.CLASS_ID
	END
END
