CREATE FUNCTION FN_STUDENT_SELECT (@STUDENT_ID VARCHAR(10))
RETURNS TABLE
AS RETURN
	(SELECT A.CLASS_ID, B.COURSE_ID, C.COURSE_FEE
		FROM RESULT A
		JOIN CLASS B ON A.CLASS_ID = B.CLASS_ID
		JOIN COURSE C ON B.COURSE_ID = C.COURSE_ID
		WHERE STUDENT_ID = @STUDENT_ID
	UNION ALL 
	SELECT NULL CLASS_ID, NULL COURSE_ID, SUM(PAYMENT) TOTAL
		FROM RESULT A
		JOIN BILL B ON A.STUDENT_ID = B.STUDENT_ID	
		WHERE A.STUDENT_ID = @STUDENT_ID)
