GO
CREATE PROC PR_BILL_INSERT
@ID VARCHAR(10), @METHOD BIT
AS
BEGIN
	INSERT INTO BILL
	SELECT A.STUDENT_ID, GETDATE() DATE_P, @METHOD METHOD_P, D.COURSE_FEE PAYMENT
	FROM RESULT A
	JOIN CLASS_DETAIL B ON A.CLASS_ID = B.CLASS_ID
	JOIN CLASS C ON B.CLASS_ID = C.CLASS_ID
	JOIN COURSE D ON C.COURSE_ID = D.COURSE_ID
	WHERE DATEDIFF(DAY,DATE_END,GETDATE()) < 0 AND A.STUDENT_ID = @ID
END
